local home = os.getenv("HOME")
return {
  home = home,
  wall_dir_default = home .. '/wallpapers',
  cache_dir = home .. '/.cache/walls/',
  wall_cache_default = home .. '/.cache/walls/wallpapers/wallpapers',
  state_cache_default = home .. '/.cache/walls/wallpapers/state',
  start_path = home .. '/.cache/walls/start',
  pid_path = home .. '/.cache/walls/pid',
  wall_dir_cache = home .. '/.cache/walls/wall_dirs',
  transition_cache_default = home .. '/.cache/walls/wallpapers/transition',
  active_dir_cache = home .. '/.cache/walls/active',
  state_id = 1,
  current_cache_index = 1,
  current_cache = 'wallpapers',
  waybar_styles = { default = 'default.css', city = 'city-foam-pine.css', not_city = 'dark-high-contrast.css'},
  transition_default = ' --transition-type grow --transition-pos top-right --transition-duration 2 --transition-fps 180',
  wallpaper_dirs = {},
  wallpapers = {},
}
