general { 
  lock_cmd = swaylock
}

listener {
    timeout = 870
    on-timeout = notify-send "You are idle 30 seconds to lock!"
}

listener {
    timeout = 900 # 5 minutes
    on-timeout = swaylock
    on-resume = notify-send "welcome back" 
}

listener {
    timeout = 1800 # 15 minutes
    on-timeout = systemctl suspend
    on-resume = notify-send "welcome back" 
}
