general { 
  lock_cmd = swaylock
}

listener {
    timeout = 870
    on-timeout = notify-send -a "hypridle" "You are idle 30 seconds to lock!"
}

listener {
    timeout = 900
    on-timeout = swaylock
}

listener {
    timeout = 915
    on-timeout = ags quit
    on-resume = bash -c 'sleep 0.5 && ags run ~/.config/ags/bar/bar.jsx &'
}

listener {
    timeout = 930 # 5:30 minutes
    on-timeout = systemctl suspend
}
