general { 
  lock_cmd = swaylock
}

listener {
    timeout = 870
    on-timeout = notify-send -a "hypridle" "You are idle 30 seconds to lock!"
}

listener {
    timeout = 900 # 5 minutes
    on-timeout = swaylock
}

listener {
    timeout = 930 # 5:30 minutes
    on-timeout = systemctl suspend
}
