$monitorMain = DP-3
$monitorSecond = HDMI-A-2

monitor=$monitorMain,preferred,auto-left,auto
monitor=$monitorSecond,preferred,auto-right,auto
monitor=,preferred,auto,auto
workspace = 1, monitor:$monitorMain
workspace = 2, monitor:$monitorMain
workspace = 3, monitor:$monitorSecond
workspace = 4, monitor:$monitorSecond

exec-once = ~/.config/hypr/scripts/monitors.sh
exec-once = ~/.config/hypr/scripts/get-updates.sh
exec-once = ~/.config/hypr/scripts/get-holidays.sh
exec-once = ~/.config/hypr/scripts/weather.sh

