windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = windowrule-3
  workspace = 4 silent
  match:class = (discord)
}

windowrule {
  name = windowrule-4
  match:title = Disk Space Info
  size = (monitor_w*0.35) (monitor_h*0.25)
  float = on
}
